alias m='mvn clean install';
alias ms='mvn clean install -DskipTests';
alias h2d='printf "%d\\n" $1';
alias his='history | grep $1';
alias c='reset';
alias pg='ps -ef | grep $1';
alias f='cd ~/IdeaProjects/';
alias p='ps -ef | grep $1';
alias t='task';
